// Auto-generated by import-notes.js - DO NOT EDIT
export const collectionSlugs = [
  "homelab-journey",
  "modern-web-fundamentals"
] as const

export type CollectionSlug = (typeof collectionSlugs)[number]
