// Auto-generated by import-notes.js - DO NOT EDIT
export const slugs = [
  "building-modern-react-typescript",
  "building-my-own-server",
  "my-cs-journey",
  "oauth2-keycloak-traefik-setup",
  "typography-showcase",
  "welcome-to-my-new-blog"
] as const

export type BlogSlug = (typeof slugs)[number]
