/**
 * Collections Module
 *
 * Functions for accessing collection data from the registry.
 * The registry is a JSON file generated by import-notes.js.
 */

import { Collection, CollectionContext, BlogPost } from '@/types/blog'
import { getBlogPost } from './registry'
import collectionsRegistry from '../../../public/collections-registry.json'

/**
 * Get all collections from the registry
 */
export function getAllCollections(): Collection[] {
  return collectionsRegistry.collections
}

/**
 * Get a single collection by slug
 */
export function getCollection(slug: string): Collection | null {
  return collectionsRegistry.collections.find(c => c.slug === slug) ?? null
}

/**
 * Get the posts belonging to a collection, in order
 */
export function getCollectionPosts(slug: string): BlogPost[] {
  const collection = getCollection(slug)
  if (!collection) return []

  return collection.postSlugs
    .map(postSlug => getBlogPost(postSlug))
    .filter((post): post is BlogPost => post !== null)
}

/**
 * Get collection context for a post (position, prev/next navigation)
 * Returns null if the post doesn't belong to a collection
 */
export function getCollectionForPost(postSlug: string): CollectionContext | null {
  const post = getBlogPost(postSlug)
  if (!post?.collection) return null

  const collection = getCollection(post.collection)
  if (!collection) return null

  const index = collection.postSlugs.indexOf(postSlug)
  if (index === -1) return null

  const previousSlug = index > 0 ? collection.postSlugs[index - 1] : null
  const nextSlug = index < collection.postSlugs.length - 1 ? collection.postSlugs[index + 1] : null

  // Get all sibling posts (other posts in the collection, excluding current)
  const siblingPosts = collection.postSlugs
    .filter(s => s !== postSlug)
    .map(s => getBlogPost(s))
    .filter((p): p is BlogPost => p !== null)

  return {
    collection,
    currentIndex: index + 1, // 1-indexed for display
    totalEpisodes: collection.postSlugs.length,
    previousPost: previousSlug ? getBlogPost(previousSlug) : null,
    nextPost: nextSlug ? getBlogPost(nextSlug) : null,
    siblingPosts,
  }
}
