name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  setup-node:
    needs: checkout-code
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

  build-project:
    needs: setup-node
    runs-on: ubuntu-latest

    steps:
      - name: Build the project
        run: npm run build && npm run export

  deploy-to-gh-pages:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
