name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      github_token:
        required: true

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}

  setup-node:
    needs: checkout-code
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

  build-project:
    needs: setup-node
    runs-on: ubuntu-latest

    steps:
      - name: Build the project
        run: npm run build && npm run export

  deploy-to-gh-pages:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: ./out
